project_id = "texnkijwcygodtywgedm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
external_url = "https://fastnow.app"

[functions.send-contact-email]
verify_jwt = false