[build.env]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.build]
cmds = ["npm ci", "npm run build"]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "npx serve -s dist -p 8080"